# Generated by Django 4.2.1 on 2023-06-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsonsjobbot.uploadedfile'),
        ),
    ]
