# Generated by Django 4.2.1 on 2023-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0007_uploadedxlsx_xlsxjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='xlsxjobs',
            name='open_or_closed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
