# Generated by Django 4.2.1 on 2023-06-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0008_xlsxjobs_open_or_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xlsxjobs',
            options={'verbose_name': 'Xlsx Jobs'},
        ),
    ]
