# Generated by Django 4.2.1 on 2023-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0010_rename_xlsxjobs_xlsxjob_alter_xlsxjob_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOWPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonum', models.CharField(max_length=100)),
                ('pos_id', models.CharField(max_length=100)),
                ('posnum', models.CharField(max_length=100)),
                ('orgnum', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('posdescnum', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('service_cat', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedSOWs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='SOWs/')),
            ],
        ),
    ]
