# Generated by Django 4.2.1 on 2023-07-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0011_sowpositions_uploadedsows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SOWPositions',
            new_name='SOWPosition',
        ),
        migrations.RenameModel(
            old_name='UploadedSOWs',
            new_name='UploadedSOW',
        ),
    ]
