# Generated by Django 4.2.1 on 2023-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0012_rename_sowpositions_sowposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowposition',
            name='posdesc',
            field=models.TextField(default='Position Description Goes Here'),
        ),
    ]
