# Generated by Django 4.2.1 on 2023-07-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0013_sowposition_posdesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sowposition',
            old_name='orgnum',
            new_name='posdesctitle',
        ),
    ]
