# Generated by Django 4.2.1 on 2023-07-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0014_rename_orgnum_sowposition_posdesctitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sowposition',
            options={'verbose_name_plural': 'SOW Positions'},
        ),
    ]
