# Generated by Django 4.2.1 on 2023-08-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0016_alter_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowposition',
            name='xlsx_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sow_positions', to='parsonsjobbot.xlsxjob'),
        ),
    ]
