# Generated by Django 4.2.1 on 2023-08-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0017_sowposition_xlsx_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sowposition',
            name='xlsx_job',
        ),
    ]
