# Generated by Django 4.2.1 on 2024-01-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0018_remove_sowposition_xlsx_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityScoreMatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_info', models.TextField()),
                ('sow_pos', models.CharField(max_length=255)),
                ('sow_info', models.TextField()),
                ('similarity_score', models.FloatField()),
            ],
        ),
    ]
