# Generated by Django 4.2.1 on 2024-01-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsonsjobbot', '0019_similarityscorematcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarityscorematcher',
            name='sow_pos',
        ),
    ]
